### ISSUE TITLE
PlugIn sammeln umstellen

### ISSUE THREAD

**Issue by sfriedo** [HPI-SWA-Teaching/SWT15-Project-04#16]
Methoden wie Install, reset, removePlugIn entfernen und Abhängigkeiten auf Instanzseite umstellen.

8 SP

**Comment by sfriedo** [comment]
Splitten

**Comment by sfriedo** [comment]
Aktuelle Iteration (28/29) : 1 SP

**Comment by NHoff95** [comment]
funktioniert jetzt, aber beim "hübsch machen" noch zu tun:
- Preferences auf Klassenseite speichern, anwenden auf Instanzseite
- verändern der Plugins, Ausblenden, ... weiter testen...
