### ISSUE TITLE
Bug - Test: Significant Duplication ERROR

### ISSUE THREAD

**Issue by naechtner** [HPI-SWA-Teaching/SWT15-Project-04#28]
Hängt von der Auswahl ab.
Siehe:
![screen shot 2015-07-01 at 14 23 01](https://cloud.githubusercontent.com/assets/11037210/8454328/c941ab00-1ffc-11e5-9a0f-d3576e0d5b1a.png)

**Comment by krono** [comment]
hatte ich mal gefixt, bitte mit mir sprechen

On 01.07.2015, at 12:00, Nico Aechtner notifications@github.com wrote:

> H�ngt von der Auswahl ab, weiteres folgt.
> 
> �
> Reply to this email directly or view it on GitHub.

## 

Tobias Pape
Research School on Service-Oriented Systems Engineering 
Software Architecture Group | http://www.hpi.uni-potsdam.de/swa/

Hasso-Plattner-Institut f�r Softwaresystemtechnik GmbH | Universit�t Potsdam
Prof.-Dr.-Helmert-Str. 2-3, D-14482 Potsdam, Germany
Amtsgericht Potsdam, HRB 12184 | Gesch�ftsf�hrung: Prof. Dr. Christoph Meinel
